// components/game/Hand.tsx
import Card from "./Card";

function Hand({cards, type}:any) {
  return (
    <div className="card-grid">
      <ul className="card-grid__list flex px-2 m-0 py-0">
        {cards && cards.map((card: any, index:number)=>(<Card card={card} type={type} key={index + card}/>))}
      </ul>
    </div>
  );
}

export default Hand;

// src/components/Hand.vue
<template>
  <v-card class="px-5">
    <h1>{{ cards.name }}</h1>
    <div v-for="card in cards.hand" :key="card.id">
      <Card
        :id="card.id"
        :front="card.front"
        :back="card.back"
        :altFront="card.value + ' of ' + card.suit"
      />
    </div>
  </v-card>
</template>
<script>
import Card from "../components/Card";

export default {
  props: ["cards"],
  components: {
    Card
  }
};
</script>
